In [2]:
!pip install agno

## Agent and Tool usage: Custom API Tool Recommendation

In [60]:
from agno.agent import Agent
from agno.models.google import Gemini
from agno.tools.api import CustomApiTools

In [4]:
import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

In [8]:
agent = Agent(
    model=Gemini(id="gemini-2.5-flash-preview-05-20"),
    tools=[CustomApiTools(base_url="https://fakestoreapi.com")],
    instructions = """
    Help me find the best products by making API calls to these endpoints:
    1. /products/categories (GET) to see all available categories
    2. /products/category/electronics (GET) to get all electronics products
    3. /products/1 (GET) to get detailed info about a specific product
    """,
    markdown=True,
    show_tool_calls=True
)

In [9]:
agent.print_response(
    "Analyze the products and recommend the best electronics item based on price and ratings."
)

┏━ Message ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                              ┃
┃ Analyze the products and recommend the best electronics item based on price  ┃
┃ and ratings.                                                                 ┃
┃                                                                              ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
┏━ Tool Calls ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                              ┃
┃ • make_request(method=GET, endpoint=/products/categories)                    ┃
┃ • make_request(method=GET, endpoint=/products/category/electronics)          ┃
┃                                                                              ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
┏━ Response (9.9s) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                              ┃
┃ Based on the analysis of electronics products by price and ratings, the      ┃
┃ Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5 ┃
┃ (Product ID: 11) is the recommended best item.                               ┃
┃                                                                              ┃
┃ Here's a breakdown:                                                          ┃
┃                                                                              ┃
┃  • Product Name: Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance   ┃
┃    Boost SATA III 2.5                                                        ┃
┃  • Price: $109                                                               ┃
┃  • Rating: 4.8 (out of 5)                                                    ┃
┃  • Number of Reviews: 319                                                    ┃
┃                                                                              ┃
┃ This product offers an excellent balance, boasting one of the highest        ┃
┃ ratings among all electronics products while maintaining a competitive       ┃
┃ price.                                                                       ┃
┃                                                                              ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

## Data Analysis Agent: Talk to your CSV file

In [11]:
import httpx
from pathlib import Path
from agno.tools.csv_toolkit import CsvTools

In [19]:
url = "https://raw.githubusercontent.com/wlodarzmar/csvToSqlTable/refs/heads/master/100%20Sales%20Records.csv"
response = httpx.get(url)

Path("/content/sales_data.csv").write_bytes(response.content)

12643

In [21]:
import pandas as pd

file_path = "/content/sales_data.csv"
df = pd.read_csv(file_path, on_bad_lines='skip')

In [29]:
df.head(20)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50
5,Australia and Oceania,Solomon Islands,Baby Food,Online,C,2/4/2015,547995746,2/21/2015,2974,255.28,159.42,759202.72,474115.08,285087.64
6,Sub-Saharan Africa,Angola,Household,Offline,M,4/23/2011,135425221,4/27/2011,4187,668.27,502.54,2798046.49,2104134.98,693911.51
7,Sub-Saharan Africa,Burkina Faso,Vegetables,Online,H,7/17/2012,871543967,7/27/2012,8082,154.06,90.93,1245112.92,734896.26,510216.66
8,Sub-Saharan Africa,Republic of the Congo,Personal Care,Offline,M,7/14/2015,770463311,8/25/2015,6070,81.73,56.67,496101.10,343986.90,152114.20
9,Sub-Saharan Africa,Senegal,Cereal,Online,H,4/18/2014,616607081,5/30/2014,6593,205.70,117.11,1356180.10,772106.23,584073.87
10,Asia,Kyrgyzstan,Vegetables,Online,H,6/24/2011,814711606,7/12/2011,124,154.06,90.93,19103.44,11275.32,7828.12
11,Sub-Saharan Africa,Cape Verde,Clothes,Offline,H,8/2/2014,939825713,8/19/2014,4168,109.28,35.84,455479.04,149381.12,306097.92
12,Asia,Bangladesh,Clothes,Online,L,1/13/2017,187310731,3/1/2017,8263,109.28,35.84,902980.64,296145.92,606834.72
13,Central America and the Caribbean,Honduras,Household,Offline,H,2/8/2017,522840487,2/13/2017,8974,668.27,502.54,5997054.98,4509793.96,1487261.02
14,Asia,Mongolia,Personal Care,Offline,C,2/19/2014,832401311,2/23/2014,4901,81.73,56.67,400558.73,277739.67,122819.06
15,Europe,Bulgaria,Clothes,Online,M,4/23/2012,972292029,6/3/2012,1673,109.28,35.84,182825.44,59960.32,122865.12
16,Asia,Sri Lanka,Cosmetics,Offline,M,11/19/2016,419123971,12/18/2016,6952,437.20,263.33,3039414.40,1830670.16,1208744.24
17,Sub-Saharan Africa,Cameroon,Beverages,Offline,C,4/1/2015,519820964,4/18/2015,5430,47.45,31.79,257653.50,172619.70,85033.80
18,Asia,Turkmenistan,Household,Offline,L,12/30/2010,441619336,1/20/2011,3830,668.27,502.54,2559474.10,1924728.20,634745.90
19,Australia and Oceania,East Timor,Meat,Online,L,7/31/2012,322067916,9/11/2012,5908,421.89,364.69,2492526.12,2154588.52,337937.60

In [26]:
db_agent = Agent(
    model = Gemini(id="gemini-2.5-flash-preview-05-20"),
    tools=[CsvTools(csvs=[file_path])],
    show_tool_calls=True,
    instructions="You are Sales Agent, analyze the data insights and provide structured responses",
    markdown=True,
)

In [27]:
db_agent.print_response(
    "what is the average of Units Sold?",
)

INFO Reading columns from file: sales_data
INFO Loading csv file: sales_data
INFO Running query: SELECT AVG("Units Sold") FROM sales_data
┏━ Message ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                              ┃
┃ what is the average of Units Sold?                                           ┃
┃                                                                              ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
┏━ Tool Calls ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                              ┃
┃ • get_columns(csv_name=sales_data)                                           ┃
┃ • query_csv_file(sql_query=SELECT AVG("Units Sold") FROM sales_data,         ┃
┃ csv_name=sales_data)                                                         ┃
┃                                                                              ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
┏━ Response (4.6s) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                              ┃
┃ The average of Units Sold is 5128.71.                                        ┃
┃                                                                              ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

In [31]:
df[df['Region'] == "Australia and Oceania"]

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50,951410.50
5,Australia and Oceania,Solomon Islands,Baby Food,Online,C,2/4/2015,547995746,2/21/2015,2974,255.28,159.42,759202.72,474115.08,285087.64
19,Australia and Oceania,East Timor,Meat,Online,L,7/31/2012,322067916,9/11/2012,5908,421.89,364.69,2492526.12,2154588.52,337937.60
23,Australia and Oceania,New Zealand,Fruits,Online,H,9/8/2014,142278373,10/4/2014,2187,9.33,6.92,20404.71,15134.04,5270.67
26,Australia and Oceania,Kiribati,Fruits,Online,M,10/13/2014,347140347,11/10/2014,5398,9.33,6.92,50363.34,37354.16,13009.18
32,Australia and Oceania,Australia,Office Supplies,Online,C,10/27/2015,158535134,11/25/2015,2924,651.21,524.96,1904138.04,1534983.04,369155.00
56,Australia and Oceania,Fiji,Clothes,Offline,C,6/30/2010,647876489,8/1/2010,9905,109.28,35.84,1082418.40,354995.20,727423.20
60,Australia and Oceania,Australia,Cereal,Offline,H,6/9/2013,450563752,7/2/2013,682,205.70,117.11,140287.40,79869.02,60418.38
76,Australia and Oceania,Federated States of Micronesia,Beverages,Online,C,10/28/2014,217221009,11/15/2014,9379,47.45,31.79,445033.55,298158.41,146875.14
79,Australia and Oceania,Samoa,Cosmetics,Online,H,7/20/2013,670854651,8/7/2013,9654,437.20,263.33,4220728.80,2542187.82,1678540.98
91,Australia and Oceania,Australia,Beverages,Offline,H,7/7/2014,240470397,7/11/2014,9389,47.45,31.79,445508.05,298476.31,147031.74

In [28]:
db_agent.print_response(
    "what `item type` is the most popular in Australia and Oceania?",
)

INFO Loading csv file: sales_data
INFO Running query: SELECT "Item Type", COUNT(*) AS popularity FROM sales_data
     WHERE Region = 'Australia and Oceania' GROUP BY "Item Type" ORDER BY
     popularity DESC LIMIT 1
┏━ Message ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                              ┃
┃ what `item type` is the most popular in Australia and Oceania?               ┃
┃                                                                              ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
┏━ Tool Calls ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                              ┃
┃ • query_csv_file(sql_query=SELECT "Item Type", COUNT(*) AS popularity FROM   ┃
┃ sales_data WHERE Region = 'Australia and Oceania' GROUP BY "Item Type" ORDER ┃
┃ BY popularity DESC LIMIT 1, csv_name=sales_data)                             ┃
┃                                                                              ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
┏━ Response (3.8s) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                              ┃
┃ The most popular item type in Australia and Oceania is Baby Food.            ┃
┃                                                                              ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

In [36]:
db_agent.print_response(
    "Which Countries have the highest Total Revenue per unit shipped?",
)

INFO Reading columns from file: sales_data
INFO Loading csv file: sales_data
INFO Running query: SELECT Country, SUM("Total Revenue") AS Total_Revenue,
     SUM("Units Sold") AS Total_Units_Sold, (SUM("Total Revenue") / SUM("Units
     Sold")) AS Revenue_Per_Unit_Shipped FROM sales_data GROUP BY Country ORDER
     BY Revenue_Per_Unit_Shipped DESC LIMIT 1
┏━ Message ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                              ┃
┃ Which Countries have the highest Total Revenue per unit shipped?             ┃
┃                                                                              ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
┏━ Tool Calls ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                              ┃
┃ • get_columns(csv_name=sales_data)                                           ┃
┃ • query_csv_file(csv_name=sales_data, sql_query=SELECT Country, SUM("Total   ┃
┃ Revenue") AS Total_Revenue, SUM("Units Sold") AS Total_Units_Sold,           ┃
┃ (SUM("Total Revenue") / SUM("Units Sold")) AS Revenue_Per_Unit_Shipped FROM  ┃
┃ sales_data GROUP BY Country ORDER BY Revenue_Per_Unit_Shipped DESC LIMIT 1)  ┃
┃                                                                              ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
┏━ Response (4.8s) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                              ┃
┃ The country with the highest total revenue per unit shipped is Angola, with  ┃
┃ a Revenue Per Unit Shipped of 668.27.                                        ┃
┃                                                                              ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

## MCP as the tool

In [41]:
!pip install mcp

In [47]:
import asyncio
import logging
from typing import Optional
import aiohttp

import nest_asyncio
nest_asyncio.apply()

In [48]:
server_url = "https://snowflake-mcp-backend.onrender.com/mcp/c9cda771-0dbf-4637-90ed-b9cf9c975098/sse"

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

In [52]:
async def check_server_health(url: str) -> bool:
    """Check if the MCP server is responding properly"""
    try:
        base_url = url.replace('/sse', '')
        health_url = f"{base_url}/health"
        print(health_url)
        async with aiohttp.ClientSession() as session:
            async with session.get(health_url, timeout=10) as response:
                logger.info(f"Health check status: {response.status}")
                if response.status == 200:
                    text = await response.text()
                    logger.info(f"Health check response: {text}")
                    return True
                return False
    except Exception as e:
        logger.error(f"Health check failed: {e}")
        return False

In [53]:
check_server_health(server_url)

In [44]:
from agno.tools.mcp import MCPTools

In [58]:
server_url = "https://snowflake-mcp-backend.onrender.com/mcp/c9cda771-0dbf-4637-90ed-b9cf9c975098/sse"

async def run_agent(message: str) -> None:
    try:
        async with MCPTools(
            transport="sse",
            url=server_url,
        ) as mcp_tools:
            agent = Agent(
                model=Gemini(id="gemini-2.5-flash-preview-05-20"),
                tools=[mcp_tools],
                markdown=True,
                show_tool_calls=True,
                instructions="You are an expert AI Assistant, answer from the tool",
            )
            await agent.aprint_response(message=message, stream=True, markdown=True)
    except Exception as e:
        print(f"SSE failed: {e}")
        # Try without SSE
        await run_agent_http(message)

async def run_agent_http(message: str) -> None:
    http_url = server_url.replace('/sse', '')
    async with MCPTools(transport="http", url=http_url) as mcp_tools:
        agent = Agent(
            model=Gemini(id="gemini-2.5-flash-preview-05-20"),
            tools=[mcp_tools],
            markdown=True,
            show_tool_calls=True,
            instructions="You are an expert AI Assistant, answer from the tool",
        )
        await agent.aprint_response(message=message, stream=True, markdown=True)

In [ ]:
if __name__ == "__main__":
    asyncio.run(run_agent("what is the data about?"))